apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dms-mail-data
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dms-config
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roundcube-db
  namespace: mailcow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
