apiVersion: v1
kind: Secret
metadata:
  name: dms-config
  namespace: mailcow
type: Opaque
stringData:
  OVERRIDE_HOSTNAME: mail.gamifying.dev
  POSTMASTER_ADDRESS: postmaster@gamifying.dev
  POSTMASTER_PASSWORD: mom2nbfYnLIt6fdWZtWaIw==
  LOG_LEVEL: info
  VIRUSMAILS_DELETE_DELAY: 7
  ENABLE_SPAMASSASSIN: "1"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "1"
  ENABLE_POSTGREY: "1"
  ENABLE_SASLAUTHD: "0"
  LDAP_START_TLS: "no"
  SASLAUTHD_MECHANISMS: pam
  SMTP_ONLY: "0"
  TLS_LEVEL: modern
  DOVECOT_MAILBOX_FORMAT: maildir
  ONE_DIR: "1"
  CHECK_CLAMAV: "0"
  AMAVIS_LOGLEVEL: "0"
