apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        email: admin@xn--myndighetsfrkortningar-4hc.nu
        privateKeySecretRef:
          name: letsencrypt-prod
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
          - http01:
              ingress:
                class: traefik
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      annotations:
        meta.helm.sh/release-name: rancher
        meta.helm.sh/release-namespace: cattle-system
      labels:
        app: rancher
        app.kubernetes.io/managed-by: Helm
        chart: rancher-2.14.0
        heritage: Helm
        release: rancher
      name: rancher
      namespace: cattle-system
    spec:
      ca:
        secretName: tls-rancher
kind: List
metadata: {}
