apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-plugins
  namespace: jenkins
data:
  plugins.txt: |
    configuration-as-code
    credentials
    credentials-binding
    git
    github
    workflow-aggregator
    pipeline-stage-view
    docker-workflow
    kubernetes
    job-dsl
