apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynforkort
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mynforkort
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-api
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-terminal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-terminal
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/registry
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailcow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mailcow
  destination:
    server: https://kubernetes.default.svc
    namespace: mailcow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: infra/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.1
    helm:
      values: |
        grafana:
          adminPassword: "admin"
          service:
            type: NodePort
            nodePort: 32745
          persistence:
            enabled: true
            size: 2Gi
          grafana.ini:
            server:
              root_url: "http://192.168.0.134:32745/"
          dashboards:
            default:
              node-exporter-full:
                gnetId: 1860
                revision: 37
                datasource: Prometheus
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: default
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        nodeExporter:
          enabled: true
        alertmanager:
          enabled: false
        kubeStateMetrics:
          enabled: true
        defaultRules:
          create: true
          rules:
            alertmanager: false
            etcd: false
            configReloaders: false
            general: true
            k8s: true
            kubeApiserverAvailability: false
            kubeApiserverBurnrate: false
            kubeApiserverHistogram: false
            kubeApiserverSlos: false
            kubelet: true
            kubeProxy: false
            kubePrometheusGeneral: true
            kubePrometheusNodeRecording: true
            kubernetesApps: true
            kubernetesResources: true
            kubernetesStorage: true
            kubernetesSystem: true
            kubeSchedulerAlerting: false
            kubeSchedulerRecording: false
            kubeStateMetrics: true
            network: true
            node: true
            nodeExporterAlerting: true
            nodeExporterRecording: true
            prometheus: false
            prometheusOperator: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
