apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mynforkort
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mynforkort
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-api
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-terminal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-terminal
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logiplan-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/logiplan-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/registry
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailcow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/mailcow
  destination:
    server: https://kubernetes.default.svc
    namespace: mailcow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: apps/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lorecreator-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/lorecreator-ai-config
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acaburaz/k3s
    targetRevision: HEAD
    path: infra/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
