apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  logiplan.server: |
    logiplan.se:53 {
      hosts {
        192.168.0.134 testapp-preview.logiplan.se
        192.168.0.134 testapi-preview.logiplan.se
        192.168.0.134 testterminal-preview.logiplan.se
        192.168.0.134 testapp-preview.logiplan.se
        192.168.0.134 sonarqube.logiplan.se
        fallthrough
      }
      forward . 8.8.8.8
    }
